import { Severity, severityLabel, type ScanResult, type Finding } from "../core/models.js";

export function renderMarkdown(result: ScanResult): string {
  const lines: string[] = [];

  lines.push(`# Sentinel Security Scan Report`);
  lines.push("");
  lines.push(`**Date:** ${new Date(result.timestamp).toUTCString()}`);
  lines.push(`**Server:** ${result.ip} (${result.os})`);
  lines.push(`**Hostname:** ${result.hostname}`);
  lines.push(`**Scan Duration:** ${(result.durationMs / 1000).toFixed(1)}s`);
  lines.push(`**Status:** ${result.summary.status}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push("| Severity | Count |");
  lines.push("|----------|-------|");
  lines.push(`| Critical | ${result.summary.critical} |`);
  lines.push(`| High | ${result.summary.high} |`);
  lines.push(`| Medium | ${result.summary.medium} |`);
  lines.push(`| Low | ${result.summary.low} |`);
  lines.push(`| Info | ${result.summary.info} |`);
  lines.push(`| **Total** | **${result.summary.total}** |`);
  lines.push("");

  if (result.findings.length === 0) {
    lines.push("No security issues found.");
    lines.push("");
    return lines.join("\n");
  }

  // Findings by severity
  lines.push("## Findings");
  lines.push("");

  const sorted = [...result.findings].sort((a, b) => b.severity - a.severity);

  lines.push("| Severity | Module | Finding | Description |");
  lines.push("|----------|--------|---------|-------------|");

  for (const f of sorted) {
    const sev = severityLabel[f.severity];
    const desc = f.description.replace(/\|/g, "\\|").replace(/\n/g, " ");
    const title = f.title.replace(/\|/g, "\\|");
    lines.push(`| ${sev} | ${f.module} | ${title} | ${desc} |`);
  }

  lines.push("");

  // Findings detail by module
  lines.push("## Details by Module");
  lines.push("");

  for (const mod of result.modules) {
    if (mod.findings.length === 0 && !mod.error) continue;

    lines.push(`### ${mod.module}`);
    lines.push("");

    if (mod.error) {
      lines.push(`> Error: ${mod.error}`);
      lines.push("");
    }

    for (const f of mod.findings) {
      lines.push(`- **[${severityLabel[f.severity]}]** ${f.title}`);
      lines.push(`  ${f.description}`);
      if (f.remediation) {
        lines.push(`  - *Remediation:* ${f.remediation}`);
      }
    }

    lines.push("");
  }

  // Module timing
  lines.push("## Module Performance");
  lines.push("");
  lines.push("| Module | Duration | Findings | Status |");
  lines.push("|--------|----------|----------|--------|");

  for (const mod of result.modules) {
    const status = mod.error ? "Error" : "OK";
    lines.push(
      `| ${mod.module} | ${mod.durationMs}ms | ${mod.findings.length} | ${status} |`
    );
  }

  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(`*Generated by [Sentinel Scan](https://github.com/sentinel-scan) v${result.version}*`);
  lines.push("");

  return lines.join("\n");
}
